### ISSUE TITLE
Showing in three columns

### ISSUE THREAD

**Issue by shinspiegel** [valentine195/obsidian-5e-statblocks#10]
Looks like something is a little bit off, 
For some reason, I'm getting the statblocks in three columns instead of two. 

<img width="1361" alt="Screenshot 2021-09-28 at 11 18 31" src="https://user-images.githubusercontent.com/30536099/135059856-ab1fd2e8-1e7e-4905-9a64-12524dd4dd72.png">

**Comment by shinspiegel** [comment]
Reloaded the app solved the issue.

**Comment by Sinled** [comment]
Have the same issue, by default stat block is displaying in 3 columns, changing zoom fixes problem for some time, but after notes switch - block is broken again

**Comment by valentine195** [comment]
This issue is fixed on the beta branch (installable via the Obsidian BRAT plugin). I’m not going to work on it on the main branch - the beta branch is about ready to go live anyway.
