### ISSUE TITLE
Feature Request: Statblock Inheritance

### ISSUE THREAD

**Issue by nonzer0value** [valentine195/obsidian-5e-statblocks#111]
I love how with this plugin you can basically take a statblock and override fields. That's great. Not knockin' it, that's why this is a feature request. :) The thing I'd like to be able to do is extend them like one would a class in a typical OOP language, or like you would an object prototype in JS.

It _kinda_ works this way now, but once you take a statblock and override certain fields, it seems like the plugin fully merges the base definition with extended fields to create a new, whole statblock. Once you save that new, derived statblock to the bestiary, changes to the old, "base" statblock do _not_ get reflected in the derived statblock.

So for example, if I have a statblock for "Monster A", let's say it has 17 hp. I want a beefier version of Monster A to use as a sergeant/miniboss. So I  create a "Monster B" like so, and I'll just add more HP for the sake of example (assume the `statblock` keyword follows the backticks in the proper manner):

```
monster: Monster A
name: Monster B
hp: 50
```

Then a render and save Monster B to the bestiary. Later I decide that all Monsters A, and all creatures derived from them, should be able to cast _earth tremor_ 1/day. So I go and add a `spells` block to the Monster A statblock, and save it.

When I render Monster B again, it will _not_ have the spells trait I gave to Monster A, as the system currently behaves.

What would be great is if the changes to Monster A propagated to all derived statblocks that have Monster A as a parent, where said changes are not explicitly overridden in those derivative statblocks.

I'm a software developer and I understand the effort on this is very high and constitutes a significant, if not complete, refactor of the data model you're using and how it's manipulated and rendered. 

What would be even way more better-er would be the ability to define "Feature" statblocks that could be used like mixins. Like Pack Tactics, you know?  It's the same for every monster that has it, only the name of the creature ever changes in that feature's description.

**Comment by valentine195** [comment]
I’ll probably just add an `extends` key

**Comment by valentine195** [comment]
`extends` has been added
