### ISSUE TITLE
How to change the dice roller trigger

### ISSUE THREAD

**Issue by f3ss1** [valentine195/obsidian-5e-statblocks#125]
Hi!

I am not really a huge specialist in Obsidian plugins so my question might be kinda dumb. What I want is to get a fork of your repo (done already) to change the text the dice roller triggers on ("on hit" in the original) to the one in my native language so it would be working for me (done already too as far as I can see).

What I do not understand is how am I supposed to use the "corrected" version of your plugin? Should I run some kind of file or what should I do to say "build it from source" in Obsidian?

Thanks in advance.

**Comment by valentine195** [comment]
You have to run the build script and put the resulting `main.js` file in the plugin folder located at `<VAULT>\.obsidian\plugins\obsidian-5e-statblocks`. Then reload Obsidian.
