### ISSUE TITLE
Basic Fate Core Layout not displaying correctly

### ISSUE THREAD

**Issue by CerealThread** [valentine195/obsidian-5e-statblocks#128]
When trying to use the Fate Core Layout, it is displayed like a 5e layout and is missing all the data besides the name of the stat block. Here's how the Fate Core example from the README is displayed.

![image](https://user-images.githubusercontent.com/65374261/210653835-62206723-c22a-4693-9e73-6ebcd77db940.png)

Additionally, when selecting the default layout, if Basic Fate Core Layout is selected, it is not saved and will revert back to "Basic 5e Layout" once the user navigates away.

**Comment by devonjones** [comment]
+1

**Comment by valentine195** [comment]
Hey, I just pushed a fix for this.
