### ISSUE TITLE
Editing a stat block layout and adding a block to one disables arrow and enter keys in the main editor

### ISSUE THREAD

**Issue by Xristopher** [valentine195/obsidian-5e-statblocks#131]
**Problem:** Creating a new layout in the plugin settings menu, or having created it, going back in and editing it, results in certain keys (e.g. arrow keys, enter key) not being recognized in the main Obsidian editor, making it difficult or impossible to edit documents without restarting Obsidian. Once restarted, the keys are functional again, until the bug is triggered again.

The trigger for the bug appears to be the process of "adding a block" to the layout. Simply clicking on the + to add the block causes the loss of functionality, even if no block is actually added. Once the add item menu is displayed, the arrow keys stop working in the main editor.

**Probable Cause:** .[jt]s is not my jam, but my guess would be that it's lines 42-60 in src/settings/suggester.ts where the keybindings take place for that menu—and that these are either not scoped correctly or they are not being unbound after they are no longer needed. If I had the time to learn .[jt]s atm, I would investigte further and create a PR, but such is not the case.

**Workaround:** Restart Obsidian after adding a new block to the stat block, or create the statblock directly in json and do not use the in-app menu for that except for minor edits.

**Comment by jhilker98** [comment]
I can also confirm this issue.
