### ISSUE TITLE
Bug: medium-long title is wrapped too early with red horizontal line

### ISSUE THREAD

**Issue by Zorgatone** [valentine195/obsidian-5e-statblocks#136]
![image](https://user-images.githubusercontent.com/2664036/216764925-1379c5ed-76c5-417a-9b0b-07a2f1ca576f.png)

The screenshot above shows two statblocks with a name that isn't super short like many creature names are (I wouldn't say that's a long one either, rather medium length).
You can see even if the name could fit on one line, it's wrapped in not two but three! lines too early, and for some reason I don't understand a red horizontal line is shown on the same row after the name text.

I'm using Obsidian v1.1.9 on Windows 10, with TTRPG Statblocks v2.24.5, and with the ITS - WOTC/Beyond - Alternate Theme

**Comment by valentine195** [comment]
This is an issue with ITS
