### ISSUE TITLE
Feature Request: Adding a section for bonus actions

### ISSUE THREAD

**Issue by spacemessenger** [valentine195/obsidian-5e-statblocks#14]
Hey there!

I'm loving this plugin so far. Would it be possible to add a section for bonus actions in addition to regular and legendary actions? It would be useful for people who make homebrew creatures that utilize bonus actions a lot more for added versatility.

Thanks!

**Comment by dschibster** [comment]
In the beta (2.0) you should already be able to do that:

In there you can copy the basic 5e Layout and edit it to your liking, and you can even add your own blocks and properties if so desired. As an example I made this here:

![image](https://user-images.githubusercontent.com/34553908/145548293-93ec4be5-5fe7-4885-94b9-b376c3d517ec.png)

Now if you create a monster with the "bonusactions" property, it will read and behave like the standard action property.

**Comment by Azraelv1** [comment]
It seems that there is either a limit to how many traits you can have or adding traits isn't working properly. I am using version 2.11.5 as of this post.
![image](https://user-images.githubusercontent.com/99816909/154290925-6744550f-4d54-4eec-8621-f9eacb5bf89e.png)

![image](https://user-images.githubusercontent.com/99816909/154287273-0f42da62-f647-49d8-a9a4-15c9de3041f4.png)
