### ISSUE TITLE
Wrong parsing of spells after 4th level

### ISSUE THREAD

**Issue by MarcoOrts** [valentine195/obsidian-5e-statblocks#19]
The spells are not parsed correctly in version 2.0.7 (that's what I installed, but Obsidian claims I have 2.0.3?!)

![image](https://user-images.githubusercontent.com/44198275/145654295-5c232053-2087-494d-8418-43a4baca7838.png)
![image](https://user-images.githubusercontent.com/44198275/145654841-73b32990-6355-48cb-b3a8-97896630d415.png)

**Comment by valentine195** [comment]
Sorry, I can’t tell what it’s doing wrong. Can you explain more?

**Comment by MarcoOrts** [comment]
Unfortunately not at the moment as I only know the symptoms but I don't really understand the code yet.
Can you give me a hint on how to debug?

**Comment by valentine195** [comment]
I meant, I can’t tell what’s wrong in the picture you showed me. It seems like it is displaying the spells you entered.

**Comment by MarcoOrts** [comment]
Oh sorry,
It misses the bullet and the cursive in the last set of spells, yes.

**Comment by valentine195** [comment]
Okay I actually think I know what is causing it. Thanks for letting me know!

**Comment by valentine195** [comment]
This should be fixed in the latest beta.

**Comment by MarcoOrts** [comment]
It does! Thank you very much!
