### ISSUE TITLE
Add Dice Roller support

### ISSUE THREAD

**Issue by valentine195** [valentine195/obsidian-5e-statblocks#2]

**Comment by umiaki** [comment]
Yes please!
Add the dice icon in preview mode next to fi. 2d6 to add new line in edit "hp: 3"
Removing the line in edit mode would default to avarage.
Thanks, great plugin!

**Comment by valentine195** [comment]
This will be in version 2.0.0

**Comment by valentine195** [comment]
Added in beta, closing this.

**Comment by umiaki** [comment]
Hi
any doc how does this work now?
Thanks

**Comment by valentine195** [comment]
See this new section of the Readme. 

https://github.com/valentine195/obsidian-5e-statblocks/tree/beta#using-dice-roller
