### ISSUE TITLE
Update Version on Obsidian Community Plugins

### ISSUE THREAD

**Issue by westriel** [valentine195/obsidian-5e-statblocks#20]
I was working with the plugin and noticed that I was still getting blocks rendering in 3 columns but #10 is marked as closed and when I checked the version it downloaded it has 1.5.7, is this the most updated and should it have fixed the 3 column bug? If not is it fixed in the beta 2.0.0 branch and should I update to that beta?

**Comment by valentine195** [comment]
It is fixed on the beta branch. That will be going out as current soon.

**Comment by westriel** [comment]
Great! I'll close this issue then
