### ISSUE TITLE
Doesn't use updated statblock in preview pages

### ISSUE THREAD

**Issue by KysaSteele** [valentine195/obsidian-5e-statblocks#22]
[data.json.txt](https://github.com/valentine195/obsidian-5e-statblocks/files/7759878/data.json.txt)

Wouldn't let me upload the json file directly, so added the txt extension. 

Seeing some oddness with the preview/read mode not using the new layout I created. Also seeing some of the "traits" not showing up. Could be something I did though. :D

**Comment by valentine195** [comment]
Okay, I fixed the layout issue in the latest beta.

The `undefined` fields unfortunately were entered incorrectly into the data, and I need to make it easier to enter this information. Now that the importing is done maybe I will tackle that next. Basically, traits require a `name` and a `desc` field. Try this data file - the correct monster is "Goblin Dog 2".

[data.json.txt](https://github.com/valentine195/obsidian-5e-statblocks/files/7759985/data.json.txt)
