### ISSUE TITLE
Statblocks Refactoring

### ISSUE THREAD

**Issue by sigrunixia** [valentine195/obsidian-5e-statblocks#238]
### Scope

An incoming major change to Obsidian Metadata will result in many of the code block and frontmatter issues that the plugin has experienced, to resolve. However, it requires some refactoring of the code base. Ideally, we'd address the multitude of trait issues at this time. 

### Discovery

Unknown at this Time. 

### Validate

No development yet.

**Comment by valentine195** [comment]
I am going to close this issue.
