### ISSUE TITLE
Add MD Links to Abilities/spells

### ISSUE THREAD

**Issue by namtrah** [valentine195/obsidian-5e-statblocks#24]
Is it possible to allow MDLinks [item](URL) in the abilities section like the following?

spells:
    - Bob is a 4th-level spellcaster. Their spellcasting ability is Wisdom (spell save DC 11, +3 to hit with spell attacks). He has the following cleric spells prepared:
    - Cantrips (at will): [light](https://www.dndbeyond.com/spells/light)
    - 1st level (4 slots): [command](https://www.dndbeyond.com/spells/command)
    - 2nd level (3 slots): [hold person](https://www.dndbeyond.com/spells/hold-person)

**Comment by valentine195** [comment]
I've actually been thinking about adding support for markdown rendering inside the text, which would allow you to just wikilink or add formatting as desired. Would that work for you?

**Comment by namtrah** [comment]
Yes, that would be great!

**Comment by dschibster** [comment]
Chiming in to say that would be fantastic!

**Comment by valentine195** [comment]
I believe this can be closed.

**Comment by LadySaga** [comment]
Since this was closed I'm guessing the feature was added. But I see no documentation of it, and I do not get it to work either.

I have a database of spells saved as notes in the vault, and have been trying to link them with the MD links just like namtrah suggested above here. But when I do, instead of getting a working link, it varies between three different results instead.
In this example, I tried to link to the spell Identify, which I have a note of, so I wrapped it in the [[Identify]] md link code, and these are the three results I get. All without an actual link.
* 1st level (4 slots): _[[Identify]]_
* 1st level (4 slots): _- - Identify_
* It just breaks completely, rendering the entire statblock invisible.

So, how do I actually use MD links in the statblocks? Or was this closed without adding the feature?

**Comment by TheAussieTinker** [comment]
Yeah it would be great to know how to implement this in obsidian

**Comment by Qtippy** [comment]
I'm not having any luck at the moment

When I do this the Block automatically enables dice parsing even if it is unselected. 

If I force dice off of the statblock for testing it simply shows the text [[Identify]] or "[[Identify]]"

**Comment by TheAussieTinker** [comment]
yeah using the quote marks and render markdown in other fields like skillsaves works but not in the spell one

**Comment by Qtippy** [comment]
Oh perfect yeah that works as a work around for now
![image](https://user-images.githubusercontent.com/26104511/180582462-596c5f1c-7990-4ce5-a3b8-223c2349e307.png)
![image](https://user-images.githubusercontent.com/26104511/180582467-83149945-147b-4868-902b-6e03c988e7c9.png)

**Comment by TheAussieTinker** [comment]
[https://www.patreon.com/posts/69424403](https://www.patreon.com/posts/69424403)

This has a guide for linking spells just make sure to:

- Add an Enter(/Return) after the | in the description followed by a space before adding the descriptor
- Then to add the bullet points same thing after the end of the prepared: add an Enter followed by a space
- Then for subsequent spells just add an Enter.

**Comment by valentine195** [comment]
2.15.0 fixes an issue with rendering markdown in spells blocks.

Please note that you will likely have to put the line in quotes:

````md
spells:
  - The archmage is an 18th-level spellcaster. Its spellcasting ability is Intelligence (spell save DC 17, +9 to hit with spell attacks). The archmage can cast disguise self and invisibility at will and has the following wizard spells prepared
  - "Cantrips (at will): [[fire bolt]], light, mage hand, prestidigitation, shocking grasp"
  - 1st level (4 slots): detect magic, identify, mage armor*, magic missile
  - 2nd level (3 slots): detect thoughts, mirror image, misty step
  - 3rd level (3 slots): counterspell, fly, lightning bolt
  - 4th level (3 slots): banishment, fire shield, stoneskin*
  - 5th level (3 slots): cone of cold, scrying, wall of force
  - 6th level (1 slot): globe of invulnerability
  - 7th level (1 slot): teleport
  - 8th level (1 slot): mind blank*
  - 9th level (1 slot): time stop
  - "* The archmage casts these spells on itself before combat."
 ````
