### ISSUE TITLE
Damage Resistance shows as "Resistances" not "Damage Resistances"

### ISSUE THREAD

**Issue by Vorthas** [valentine195/obsidian-5e-statblocks#26]
When adding the damage_resistances string into the statblock code, like so

![image](https://user-images.githubusercontent.com/24818280/148332700-9a66de38-3b15-4883-b778-1b4315b8fb94.png)

The result looks more like this

![image](https://user-images.githubusercontent.com/24818280/148332730-dc0fe1a8-34ea-42d7-8c24-7caf9bcdc9c4.png)

Immunities and Vulnerabilities display as normal per the 5e statblock convention (even though the order is wrong, Vulnerabilities should be on top, then resistances, then immunities), but Resistances doesn't have the word Damage in front of it.  Seems like the change should be in src/renderer/statblock.ts on line 195, since it shows only "Resistances" there and not "Damage Resistances", though I didn't see that file in the beta branch so unsure if this file has been removed for something else?

Using Obsidian v0.13.19 with version 11.5.8 of the 5e Statblocks plugin and no other community plugin.

**Comment by valentine195** [comment]
This is fixed in the beta (2.2.4).
