### ISSUE TITLE
Allow for Monster Statblock Overwriting 

### ISSUE THREAD

**Issue by Jack-Smith-Hocking** [valentine195/obsidian-5e-statblocks#27]
This might be very niche, I might be the only one who wants this but it would be handy if you could overwrite an existing monster when saving from the preview pane:

![statblock](https://user-images.githubusercontent.com/73635494/148379976-25fbe828-b842-4515-8730-fea1bc042de6.PNG)

So basically what I want (and thought would happen given the warning in the settings menu) is for when you click save here it will overwrite the statblock data of a monster with the same name.

This plugin has been really cool so far, haven't scratched the surface but I just thought this would be nice so that I can preview my updates while I make them.

**Comment by valentine195** [comment]
This is now possible on the latest beta - any monster can be saved, but you will receive a warning if it will overwrite.
