### ISSUE TITLE
Name with # doesn't allow escape.

### ISSUE THREAD

**Issue by farling42** [valentine195/obsidian-5e-statblocks#28]
In my Realm Works to Obsidian converter, I'm finding quite a few creatures have a name with "#number" at the end.

When this gets converted to your statblock, it looks like:

```
name: Creature #3
```

The #3 isn't displayed by your plugin, maybe because it thinks it is a tag.  If I put "\\" in front of "#3" to escape the nature of the #, then the statblock is displayed with "\\#3" at the end (the "\\" escape character is not removed).

**Comment by valentine195** [comment]
Yeah, this is because the stat block is parsed as YAML, where the `#` is a comment. 

This can be solved by me replacing escaped characters easy enough post-parse.
