### ISSUE TITLE
Feature Request: Custom statblock colour settings

### ISSUE THREAD

**Issue by Jack-Smith-Hocking** [valentine195/obsidian-5e-statblocks#29]
I like the D&D statblock aesthetic but it can be a bit bright when on a dark background (especially with the glow). If it's possible, and easy enough, it would be great to have some simple colour options for the statblock. Nothing fancy, could even just be something like text, background, and border. Also an option to toggle the glow would be great.

I appreciate the hard work, it's a really cool plugin.

**Comment by valentine195** [comment]
The CSS can be customized with a CSS snippet. See [here](https://github.com/valentine195/obsidian-5e-statblocks#customizing-the-css). This includes the background glow.

If you are on the beta, you can target your custom statblock layouts as well.
