### ISSUE TITLE
Optional stats-field?

### ISSUE THREAD

**Issue by mhofherr** [valentine195/obsidian-5e-statblocks#3]
Hi Jeremy,
would it be possible to add an optional field to 5e-statblocks? Something like:
"fage_stats: [number, number, number, number, number, number, number, number, number]"

I am using Fantasy AGE and can recycle almost all fields of 5e statblocks, with the exception of "stats". Fantasy AGE uses instead the following 9 stats: 
- Accuracy
- Communication
- Constitution
- Dexterity
- Fighting
- Intelligence
- Perception
- Strength
- Willpower

**Comment by valentine195** [comment]
Should be easy enough. Can you show me an example of a Fantasy AGE statblock to reference visually, or would they just replace the standard 5e table?

**Comment by mhofherr** [comment]
It would just replace the results from the stats-line from 5e (but due to 9 instead of 5 values, probably require 2 lines?). 
See screenshot of Fantasy AGE statblock from a character below:
<img width="533" alt="Screenshot 2021-07-17 at 14 54 52" src="https://user-images.githubusercontent.com/7408042/126037578-f7ca54e6-f8df-4855-9df9-3b8b8416ab88.png">

Abbrevations are: 
- ACC
- COM
- CON
- DEX
- FGT
- INT
- PER
- STR
- WIL

**Comment by valentine195** [comment]
Added in 1.5.0

**Comment by mhofherr** [comment]
Thanks for adding. I did some testing and have one observation:
- second part of stats does (in my test) not reflect values entered by me (see values and screenshot for explanation)

`fage_stats: [3, 4, 2, 5, 3, 0, 1, 3, 8]`

Result:
<img width="420" alt="Screenshot 2021-07-24 at 10 52 55" src="https://user-images.githubusercontent.com/7408042/126863228-3429c16f-969e-4647-b22b-bf24ec0f4574.png">

**Comment by valentine195** [comment]
Oh whoops! I had it working then made a small change and broke it. Quick fix though, once I have a bit of time to work on it.

**Comment by valentine195** [comment]
Hi, this should be fixed in 1.5.1.

**Comment by mhofherr** [comment]
Tested => worked :-)
Thanks a lot!
