### ISSUE TITLE
Feature Request: A generic table and list of strings & traits

### ISSUE THREAD

**Issue by VeroVerro** [valentine195/obsidian-5e-statblocks#30]
Hi!

So I'm finally trying out the beta and building a fate core layout for NPCs (since fate doesn't have monsters as such, just entities that all have basically the same properties), and I could really use a simple list of strings. It could look like spells, for example, just without any constraints about content. If it could also have a section heading, like Traits, that'd be great too :) It'd be perfect for aspects of an entity. Thank you!

Another one that'd be really appreciated is a generic list of traits. It'd look just like traits (like Actions or Legendary actions), but it'd not be tied to a dictionary (or maybe a custom dictionary could be used? that'd be awesome too, that way I could build a library of stunts, for example :D but I can do that in a separate note anyway, and just copy-paste, so that's good too). So I could write something like:

```statblock
skills:
    - [Fantastic (+6), Deceive and Fight]
    - [Superb (+5), Shoot, Burglary]
stunts:
    - [Takes One to Know One, Use Deceive instead of Empathy to create an advantage in social situations.]
```

Same with a generic table, without the calculations - so without the stuff in parenthesis if I make my own headings:
<img src="https://user-images.githubusercontent.com/17042871/149231053-1dbe38cb-0cea-411a-b482-c4713e4ffb19.png" width="300">

I'm attaching a main NPC stats as an example. (This image is not exhaustive though, just fyi, by default the NPC can also have items, and fate is meant to be extensible, so they'd often have more properties, based on the game setting.)

<img src="https://user-images.githubusercontent.com/17042871/149224422-1f8227ac-eae3-4265-91d5-e906ce186919.png" width="200">

**Comment by valentine195** [comment]
I'm working on this, but this:

```
skills:
    - [Fantastic (+6), Deceive and Fight]
    - [Superb (+5), Shoot, Burglary]
stunts:
    - [Takes One to Know One, Use Deceive instead of Empathy to create an advantage in social situations.]

**Comment by VeroVerro** [comment]
Could there be some kind of whitelist of allowed monster property names then? because this is what it looks like:

<img src="https://user-images.githubusercontent.com/17042871/149395780-e6183332-a913-4d7f-98be-122aa0ae3e0d.png" width="200">

The one under "Traits" heading is a traits section that I copied as is from the stunts property and just renamed it to "traits", and added a Traits block linked to "traits". The block is the same as those for "stunts" and "skills", and I also tried creating one with "traits" property, checking if it shows up and then renaming the property to a random word, which is when it went back to undefined.

This is what it is in the layout builder:

<img src="https://user-images.githubusercontent.com/17042871/149396329-0a7897f5-857c-4b50-8ee0-7a3297635e58.png" width="200">

<img src="https://user-images.githubusercontent.com/17042871/149396447-40b6b2bc-2312-41bc-a94f-97b45953810d.pn" width="200">

(I turned off the dice parsing & conditional to keep any possible side effects minimal, but it does the same with them on.)

Does it work for you though? So we know if it's something on my computer. I also tried it on a new empty vault with no themes or anything else enabled though, and it still showed text when it was "traits" property but not when it was "stunts", all things otherwise being equal.

**Comment by valentine195** [comment]
The block creator may be a little misleading, yeah. The "standard" monsters only have the 5e properties (as in, they do not have a "Stunts" property on them). You would have to create a monster JSON and add that property yourself. I will make it easier to do that - right now you either have to click the edit button on a monster in your bestiary or edit the plugin `data.json` file directly.

**Comment by valentine195** [comment]
Once I have some more time I'll make a wiki on this repo with some steps to set up a custom layout.

**Comment by VeroVerro** [comment]
Okay, I'm not sure if I did it right - probably not lol bc there already were stunts, but what I did was save the monster as homebrew from the note, then clicked edit on it in the ttrpg plugin homebrew section. It did already have the stunts and skills though (and still showed them as undefined in the note), but they had a different format than traits, look:

![image](https://user-images.githubusercontent.com/17042871/149399955-482609ff-c123-47d7-8413-439a7272ea1d.png)

Also, I tried to remove the empty "actions" property and that gave me an error in the console:

![image](https://user-images.githubusercontent.com/17042871/149400062-3dd1f50c-30a2-4896-95ce-ad9c7fb5d168.png)

Again, I realize that's probably not what you meant but thought you might want to know anyway :D I'm going to look at that `data.json` file in the plugin now.

**Comment by valentine195** [comment]
Please update to the latest beta and try again.

**Comment by VeroVerro** [comment]
Thank you!

I updated and tried out the new text block, and it works nicely combined with the markdown rendering :D 

What I had originally in mind was a list of strings (like spells) that would be formatted like this:

```statblock
aspects: 
    - Main aspect is this
    - Trouble aspect is this
    - Third aspect is this
```

Which renders this:

<img src="[url](https://user-images.githubusercontent.com/17042871/149475059-52bdd8e2-8a27-40bd-aa84-76f7fdf3aad1.png)" width="200">

But since this is text and it can be set to parse markdown, I can also just write it in one line with `<br>` and it shows them on new lines - I like this a lot, it makes it super customizable :D I wrote my original format in the statblock block (and the results) too though, because I'd have expected it to parse the markdown list. Still, I think I prefer it this way, it has more styling options since it can parse html :D

```statblock
aspects: Main aspect is this<br>Trouble aspect is this<br>Third aspect is this
```

<img src="[url](https://user-images.githubusercontent.com/17042871/149475130-50b44c79-40ac-46a3-a5d6-7980434b6ec9.png)" width="200">

For example, this also works:

```statblock
aspects:
    <div>Main aspect is this</div>
    <div>Trouble aspect is this</div>
    <div>Third aspect is this</div>
```

**Comment by valentine195** [comment]
this works

```statblock
monster: Ancient Black Dragon
layout: Text
name: Paarthurnax
stunts: "
  - Test\n
  - Test 2\n
  - [[Statblock Testing]]"
```

**Comment by VeroVerro** [comment]
It does! Thanks for the tip <3 So yeah, I'm super happy with this update, thank you :)

**Comment by valentine195** [comment]
Can this be closed?

**Comment by VeroVerro** [comment]
yes, thank you!
