### ISSUE TITLE
Obsidian loses ability to react to up arrow, down arrow and Enter key after moving around groups in the layout editor

### ISSUE THREAD

**Issue by Duke-Igthorn** [valentine195/obsidian-5e-statblocks#42]
On occasion, after moving groups around in the layout editor for custom statblock sheets, when returning to a pane, the up arrow, down arrow and enter key become unresponsive. Left and right still work and it is still possible to type, but a line break isn't happening anymore and navigating the cursor becomes nigh impossible.
When restarting the app, the problem is resolved.

**Comment by lolbat** [comment]
Oddly Enter doesn't work but Shift-Enter does. This isn't recognised as a LF character though and causes issues

**Comment by LadySaga** [comment]
I've noticed the same issue, thou Shift+Enter doesn't work either for me.
Only fix I've found so far is to restart Obsidian entirely.

**Comment by nikodemus** [comment]
Happens here as well.

**Comment by valentine195** [comment]
This should be fixed in the latest release
