### ISSUE TITLE
Homebrew Creatures settings cannot filter; nested creature values in window.bestiary

### ISSUE THREAD

**Issue by bost-ty** [valentine195/obsidian-5e-statblocks#46]
Thanks again for this plugin. I'm not familiar with Svelte or TypeScript, but this plugin makes me want to learn so I can contribute.

My apologies for the size of the inline screenshots.

I also have Dice Roller, Initiative Tracker, and Admonition installed and enabled. I use iCloud Drive to sync the contents of this Obsidian vault; during testing, sync is complete and all synced files are downloaded to the test computer.

The Homebrew Creatures section of the settings menu for the plugin does not display/filter creatures; the "Filters" toggle has one checkbox that doesn't seem to do anything when toggled (screenshot attached). Typing the name of a creature in the text input doesn't display. (When using a non-default theme,"Minimal", the checkbox is 90% hidden off to the left side; the screenshot was taken with Default dark mode for this reason.)

![Screenshot 2022-03-10 133513](https://user-images.githubusercontent.com/61333914/157758760-cb2fa189-2ae5-465f-8e91-96e598b82ac7.png)

I have confirmed the stored name by checking the plugin's `data.json` as well as using a dataviewJS + customJS solution to output the contents of `app.plugins.getPlugin("obsidian-5e-statblocks").bestiary` and `bestiary.values()` to a test file in Obsidian. Interestingly, all of my custom creatures seem to be indented about 3 or 4 levels deeper than the default bestiary monsters in both cases, and may even be nested inside of each other and duplicated with old content? Additional screenshot:

![Screenshot 2022-03-10 134512](https://user-images.githubusercontent.com/61333914/157759915-3e7d3535-1115-4e8b-8d6c-75431e956059.png)

Not shown: this is nested inside of another `creature: creature: ` block above of the same creature. The values for these creatures/nested creatures are all identical to the original values I made for the monster, and do not update to the updated values I've made on this same creature in the same note. Instead, an additional entry has been made to the bottom of the bestiary with the latest values (likely generated from running the plugin's Parse frontmatter command). I believe the nested creatures are counted by the settings menu Homebrew Creatures section, but are not updated/overwritten by the Parse frontmatter command (maybe it's not finding the creature values where it expects them to be?)

If it helps, Initiative Tracker is synced & counts the same number of creatures (15, in my case) as the Homebrew Creatures menu displays -- but the stats it pulls are the out of date original stats, not the newest version of the creature, and I cannot change it from the I.T. sidebar.

Happy to provide files/information as needed to troubleshoot.

- bost-ty

**Comment by valentine195** [comment]
Is this from a creature defined in frontmatter?

**Comment by bost-ty** [comment]
Yes, frontmatter creature in a dedicated note.

**Comment by bost-ty** [comment]
* Just saw your edit. I'm up to date, so I'm going to try removing everything from `data.json` and see what is repopulated.

**Comment by bost-ty** [comment]
Deleted contents of `monsters` from data.json and saved. Reopened Obsidian, Homebrew Creatures menu displays 0 creatures (yay!), homebrew creatures are not coming up in the bestiary list (yay!). 

Ran Parse frontmatter..., monsters show up correctly in their embeds AND in Initiative Tracker! And now they have the `mtime` property, which I didn't notice before in the nested creatures. And the nesting is gone too!

Looks like cleaning out the old homebrew monsters list by editing data.json did the trick. Thank you!

If I edit the frontmatter (changing hit-die, in this case, because I can see the results in I.T. too) and re-run Parse: no duplicate entries, no nesting, the old entry is correctly removed/overwritten. Brilliant.

I'm still not able to find any of them through the Homebrew Creatures input in settings -- is that meant to pull frontmatter-made creatures, or just creatures imported from different sources?

**Comment by valentine195** [comment]
Okay, they should show up in settings and initiative tracker should be pulling directly from the stat block bestiary. I’ll take a look, but it probably won’t be until tomorrow.

**Comment by bost-ty** [comment]
As soon as I read your comment and go look, now I see them in the settings (with "undefined" beneath their names, I assume that's the source like "SRD" is for the default creatures). I don't know what changed to have them visible now vs. 10 minutes ago after I cleared out the old monsters.

Testing a little further with the Initiative Tracker HP not changing, my confusion was that the embedded statblocks use the average of the hit die as initial HP, but if there's an HP value added to the frontmatter, I.T. uses that value and ignore the average. No big deal there, and helps with customization if one did want a specific non-average default HP value for a creature.

If further issues occur, I'll spend a little more time troubleshooting on my own before I jump to writing an issue. Thank you very much for your help!

**Comment by valentine195** [comment]
Awesome, everything is working as expected then?

**Comment by bost-ty** [comment]
Yes, thank you!

**Comment by valentine195** [comment]
Great 👍🏼
