### ISSUE TITLE
Spell block not support link

### ISSUE THREAD

**Issue by Cinnius** [valentine195/obsidian-5e-statblocks#52]
I'm currently creating a custom layout for starfinder and i want to link the page of the spell in the spell block section of my statblock but, even after activating the "markdown" function on the layout option the link for other page don't work. I tested the same setting with other layout block (mainly trait block) and in this block the link work correctly.

it's possible to implement or correct the eventual bug for this fuction?
I love the plugin and if i can implement link to page or webpage for the spell this can become so much helpful for my statblock.
Thanks in advance!

**Comment by LangyMD** [comment]
What's actually implemented doesn't work for the native spell block. What's described in the Patreon post that's linked does work, but it's a bit of work to get it functional. Would be better if the native spell block could handle links.

**Comment by valentine195** [comment]
2.15.0 fixes an issue with rendering markdown in spells blocks.

Please note that you will likely have to put the line in quotes:

````md
spells:
  - The archmage is an 18th-level spellcaster. Its spellcasting ability is Intelligence (spell save DC 17, +9 to hit with spell attacks). The archmage can cast disguise self and invisibility at will and has the following wizard spells prepared
  - "Cantrips (at will): [[fire bolt]], light, mage hand, prestidigitation, shocking grasp"
  - 1st level (4 slots): detect magic, identify, mage armor*, magic missile
  - 2nd level (3 slots): detect thoughts, mirror image, misty step
  - 3rd level (3 slots): counterspell, fly, lightning bolt
  - 4th level (3 slots): banishment, fire shield, stoneskin*
  - 5th level (3 slots): cone of cold, scrying, wall of force
  - 6th level (1 slot): globe of invulnerability
  - 7th level (1 slot): teleport
  - 8th level (1 slot): mind blank*
  - 9th level (1 slot): time stop
  - "* The archmage casts these spells on itself before combat."
 ````

**Comment by LangyMD** [comment]
Thanks!
