### ISSUE TITLE
Add in the ability to delete the standard SRD monsters

### ISSUE THREAD

**Issue by monyarm** [valentine195/obsidian-5e-statblocks#57]
I'm using this plugin for pathfinder, i've created a custom layout, and it's worked well so far, problem is i've created a statblock called "Kobold", and now want to inherit from it in my other statblock "Yusdrayl". But instead it inherits from the SRD Kobold.

**Comment by Chr9sG** [comment]
I use the plugin for both 5e and Rolemaster. When I create a modified statblock for Rolemaster creature that is the 5e equivelent I just change the name. e.g., I have "Kobold" for 5e which draws from the SRD Kobold and "Koboldrm" which is my custom Kobold.

**Comment by valentine195** [comment]
There was an issue that caused the plugin to require a restart before homebrew creatures would be available in the bestiary. Could that be the issue? I just fixed that one recently.

**Comment by valentine195** [comment]
Closed
