### ISSUE TITLE
Importing homebrew does not work

### ISSUE THREAD

**Issue by P4r4b0x** [valentine195/obsidian-5e-statblocks#6]
Hi there,

when trying to import a DnDApp or 5etools file with this plugin, nothing happens.
The same procedure *does* work for the current version of your initiative tracker though.

Cheers P4r4b0x

**Comment by P4r4b0x** [comment]
DnDAppFilesImport.ts:95 Uncaught (in promise) TypeError: Cannot read property 'textContent' of undefined
    at getTraits (eval at <anonymous> (app.js:1), <anonymous>:20411:21)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:20385:44)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:38:71)
    at new Promise (<anonymous>)
    at __awaiter (eval at <anonymous> (app.js:1), <anonymous>:34:12)
    at FileReader.reader.onload (eval at <anonymous> (app.js:1), <anonymous>:20347:40)

Thats the console output.

I'm using windows 10 
obsidian v0.12.12
5e-statblocks 1.5.1

**Comment by valentine195** [comment]
Thanks. Can you send me the XML file?

**Comment by P4r4b0x** [comment]
How?

**Comment by valentine195** [comment]
Good point! Is it a file of a module? Can you let me know the module name?

**Comment by P4r4b0x** [comment]
It's for example the Curse of Strahd DnDAppFile. Its an XML

**Comment by valentine195** [comment]
Yep - I think the one you are importing may just be formatted differently than the one I referenced when I built the importer, so I was going to look at the difference.

For now I added in some error checking to skip ones that break in 1.5.2

**Comment by P4r4b0x** [comment]
Thank you for the quick reply 👍

**Comment by P4r4b0x** [comment]
Works now 👍
