### ISSUE TITLE
[BUG] Layout issue when using Render as Markdown blocks

### ISSUE THREAD

**Issue by JYCasalis** [valentine195/obsidian-5e-statblocks#60]
When using a custom layout where some blocks, such as Actions for example, are configured as 'Render as Markdown', the layout is slightly broken as unexpected empty lines appear (don't worry about the dice not being visible, that's expected (for now.....) when using markdown):

Example for the Goblin:
![image](https://user-images.githubusercontent.com/9211839/169607158-a1772011-f609-4735-b234-978179771f23.png)

And here's the "normal" layout (i.e. without Render as Markdown):
![image](https://user-images.githubusercontent.com/9211839/169607225-7e3b0b54-6641-40dc-aa62-6d7f2825d57f.png)

@valentine195 

I had been able to "fix" this issue by changing the following in MarkdownHolder.svelte:
`<div use:markdown />`

into something I'm not proud of... (especially the :global part)
```
<div class="statblock-markdown" use:markdown />

<style>
    .statblock-markdown {
        display: inline;
    }
    :global(.statblock-markdown p) {
        display: inline;
    }
</style>
```

Would you have a better fix or is this more ok than I think? 

Thanks for your help.

**Comment by valentine195** [comment]
Hmm, I would probably do it this way so it’s still scoped:

```css
.statblock-markdown :global(p) {
        display: inline;
}
```

**Comment by JYCasalis** [comment]
OK I'll make a PR with this then. 

Thanks!

**Comment by valentine195** [comment]
Merged
