### ISSUE TITLE
How to save Homebrew monsters?

### ISSUE THREAD

**Issue by WychWitch** [valentine195/obsidian-5e-statblocks#7]
Hello! I'm just starting to use this and I cant figure out how to add my homebrew monster to 5e statblock settings. I've created a statblock for it in its own file, but it wont appear in the statblock settings.  Is there some other way to add it I don't know about? Thank you in advance

**Comment by valentine195** [comment]
There should be a “save” button in the top right of the stat block in preview mode.

**Comment by WychWitch** [comment]
THAT WAS IT thank you!! I saw that save button but had no idea what it did (i thought it would just export the statblock to a json or something, similar to how the picture saves a png)

thanks so much for your instant response!!
