### ISSUE TITLE
Bug: Colons break stat blocks when used in descriptions of traits and actions [Minor Issue] [Workaround Included]

### ISSUE THREAD

**Issue by Charles-Thacher** [valentine195/obsidian-5e-statblocks#71]
Example:
I want to tweak the Specter's (D&D 5e Monster Manual) life drain action, specifically re-add it with a different description. RAW, it reads as such:
>Melee Spell Attack: +4 to hit, reach 5ft., one creature. Hit: 10 (3d6) necrotic damage. The target must succeed on a DC 10 Constitution saving throw or its hit point maximum is reduced by an amount equal to the damage taken. This reduction lasts until the creature finishes a long rest. The target dies if this effect reduces its hit point maximum to 0.

I want to change some of the numbers. Since only the first line is important for this issue, I will just post that:
>Melee Spell Attack: +4 to hit, reach 5ft., one creature. Hit: 5 (2d4) necrotic damage. The target must succeed on a DC 8 Constitution saving throw...

In the format, to override the RAW statblock, I write the following into Obsidian:
>\```statblock
>monster: Specter
>actions:
>  \- name: Life Drain
>    desc: Melee Spell Attack: +4 to hit, reach 5ft., one creature. Hit: 5 (2d4) necrotic damage. The target must succeed on a DC 8 Constitution saving throw or its hit point maximum is reduced by an amount equal to the damage taken. This >reduction lasts until the creature finishes a long rest. The target dies if this effect reduces its hit point maximum to 0.
>\```

However, the statblock breaks and will not render. I have to remove the colons in the description (one after "Attack," one after "Hit.") Therefore, custom statblocks cannot be written in the same format as the 5e stablocks.

This also occurs when creating purely custom statblocks using the formatted provided by this plugin.

I don't imagine there is an easy fix, but hopefully it will at least be helpful to bring it to your attention.

**Comment by valentine195** [comment]
Hi, please see the warning callout in this section :)

https://github.com/valentine195/obsidian-5e-statblocks#usage
