### ISSUE TITLE
Statblock always uses two columns if Readable line length is off unless one column is explicitly specified

### ISSUE THREAD

**Issue by LangyMD** [valentine195/obsidian-5e-statblocks#83]
The Statblock seems to not bother using the code to determine how many columns to display a creature if the Obsidian-wide "Readable line length" setting is turned off.

I'd much prefer to use the column number behavior that works with "Readable line length" on but have the actual "Readable line length" setting off (ie, small statblocks should be a single column instead of always being two columns even for the smallest of possible statblocks).

**Comment by valentine195** [comment]
I think this might've been fixed in the latest release... can you check?

**Comment by LangyMD** [comment]
Checked and it is indeed fixed. Thanks!
