### ISSUE TITLE
Where to access an imported monster from 5eTools?

### ISSUE THREAD

**Issue by matt-evangelidis** [valentine195/obsidian-5e-statblocks#9]
Hi Jeremy,

I've been attempting to import monsters from 5eTools, and despite the notification popping up "Succesfully imported 1 monsters", there seems to be no indication it's actually working. I haven't been able to use the monster field directly inside the statblock in a note to add anything other than the included SRD monsters, as well as homebrew monsters I've already added.

Additionally, no matter how many monsters are actually included in the json file I give, the notification only ever displays as "Succesfully imported 1 monsters".

Any help would be much appreciated.

**Comment by valentine195** [comment]
Imported monsters should appear in the Homebrew Monsters list below the import buttons in Settings. 

Additionally, they will be put in the `data.json` file in `<VAULT>/.obsidian/obsidian-5e-statblocks`. 

If the monster isn't in the Homebrew Monster list though then there was actually an error saving it. I'll take a look.

**Comment by ImQuibsY** [comment]
I'm also having an issue with importing 5e Tools bestiary. Is it possible to get a small how-to or something like that?

**Comment by valentine195** [comment]
> I think the "daily" and "will" sections under spellcasting are causing the issue.

This issue should be fixed.

> I'm also having an issue with importing 5e Tools bestiary. Is it possible to get a small how-to or something like that?

Sorry, I will work on improving the error handling. Not sure how it’s saying it was successful but not actually succeeding… what monster are you trying?

**Comment by ImQuibsY** [comment]
My attempt was to import more than one creature at once, so I was importing a list of creatures. On 5eT I went to the bestiary, added monsters to a list using the + option, right click the list -> Download JSON Data and trying to import that. No matter if that is one creature or multiple I get the same result, which is the "successfully imported 1 monsters" and then nothing. For reference I've tried to import only Aarakocra in that way and it doesn't work.

**Comment by Tahlwyn** [comment]
Having the same issue here. It looks like it works fine with one monster at a time but it does not seem to accept arrays.

**Comment by valentine195** [comment]
Version 2.0.0 will accept arrays.

**Comment by ImQuibsY** [comment]
> Version 2.0.0 will accept arrays.

Awesome! Is there any expectation when 2.0.0 would be ready to go, or is that still up in the air? Is there anything I could do to help?

**Comment by valentine195** [comment]
The latest beta should have the ability to mass-import creatures from 5e.tools, either from the bestiary data files or going to the bestiary on the website, adding monsters to a list using the + option, and right clicking the list -> Download JSON Data.

Single creatures may still be imported as well.

**Comment by valentine195** [comment]
Fixed in beta, closing this.
