### ISSUE TITLE
bug: links don't get rendered anymore in Text and Traits blocks

### ISSUE THREAD

**Issue by VeroVerro** [valentine195/obsidian-5e-statblocks#96]
It doesn't matter if the option for trying to render wikilinks is on or off. This definitely used to work but I'm not sure when it stopped, as I've been away for a month or so.

An example is in my [Basic Fate Core Layout](https://github.com/valentine195/obsidian-5e-statblocks#full-example-1): literally if you copy/paste the statblock from this example, you'll see that the links that worked on the screenshot below the statblock in the `aspects` and `items` sections (block types `Text` and `Traits`, respectively) no longer render or function as links.

Thank you for your continued support and creativity!

**Comment by valentine195** [comment]
Have you updated to today's release?

**Comment by VeroVerro** [comment]
yeah, I was hoping it'd work with that but it didn't help :(

**Comment by VeroVerro** [comment]
There's no error in the console when rendering, it just treats the links as if they were text, stripping the `[[]]` completely. For a link with alias or to a section, it renders it as pure text looking like `Weapons#^b1176e|(stats)` (from a link `[[Weapons#^b1176e|(stats)]]`)

**Comment by VeroVerro** [comment]
@valentine195 thank you! It works well now, except if the statblock is defined in frontmatter (sorry, I didn't think of that as being different to solve). The errors are (for two different statblocks defined in frontmatter):

```
plugin:obsidian-5e-statblocks:430
Obsidian Statblock Error:
SyntaxError: Unexpected token < in JSON at position 112
```

and

```
plugin:obsidian-5e-statblocks:430
Obsidian Statblock Error:
SyntaxError: Unexpected token < in JSON at position 229
```
